### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by yui-regalia** [Teeoo/v2p-client#2]
1. minishell右滑打开在手机上太容易误触打开   建议限制区域在紫色范围内
2. rewrite和task  名字和地址位置显示位置太短了，有换行让显示完整更好 
![微信图片编辑_20211201225017](https://user-images.githubusercontent.com/80944814/144258393-f2ee3d42-c664-4b55-86fe-bd51767ddea5.jpg)

**Comment by Teeoo** [comment]
rewrite改了下task要大改往后拖拖
